/*
 * NFT Storage API
 *
 * # API Reference 
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NftDeals {
    /// Overall deal status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "deals", skip_serializing_if = "Option::is_none")]
    pub deals: Option<Vec<crate::models::Deal>>,
}

impl NftDeals {
    pub fn new() -> NftDeals {
        NftDeals {
            status: None,
            deals: None,
        }
    }
}

/// Overall deal status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ongoing")]
    Ongoing,
    #[serde(rename = "finalized")]
    Finalized,
}

