/*
 * NFT Storage API
 *
 * # API Reference 
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnauthorizedErrorResponse {
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::UnauthorizedErrorResponseError>>,
}

impl UnauthorizedErrorResponse {
    pub fn new() -> UnauthorizedErrorResponse {
        UnauthorizedErrorResponse {
            ok: None,
            error: None,
        }
    }
}


